---
locale: es
tags: []
layout: input_right
editor: single_choice
type: problem
extra_visible: false
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '1'
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '34'
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '2'
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '3'
  checked: false
name: Razonamiento lógico
